import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import './globals.css'
import { ReactQueryProvider } from '@/providers/ReactQueryProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const te = false;

  return (
    <html lang="pt">
      <body className="flex flex-col h-screen w-screen">
        <ReactQueryProvider>
          {te && <header className="w-full h-[8%] bg-violet-300 text-white">Header</header>}
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  )
}
